name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  omnix-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          diagnostic-endpoint: false

      # Cache and restore Nix build results
      - uses: DeterminateSystems/magic-nix-cache-action@v9

      # Install Omnix
      - name: Install Omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"

      # Run comprehensive CI with Omnix (builds all outputs, runs checks, etc.)
      - name: Run Omnix CI
        run: om ci

      # Smoke test: run script against `tests/smoke.cook`
      - name: Run smoke test
        run: |
          nix run . -- tests
          echo "Generated phrases.json:"
          jq . phrases.json
          test "$(jq 'keys | length' phrases.json)" -gt 0