name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          diagnostic-endpoint: false

      # Cache and restore Nix build results
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      # Check formatting with Alejandra
      - name: Run Alejandra fmt – check only
        run: |
          nix develop --command alejandra --check .

  nix-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          diagnostic-endpoint: false

      # Cache and restore Nix build results
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      # `nix flake check` (ensures package builds on all supported systems)
      - name: flake check
        run: nix flake check

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          diagnostic-endpoint: false

      # Cache and restore Nix build results
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      # Smoke test: run script against `tests/smoke.cook`
      - name: Run smoke test
        run: |
          nix run . -- tests
          test "$(jq 'keys | length' phrases.json)" -gt 0